name: confoid-ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9.10"]
        experimental: [false]
        include:
          - python: "3.10"
            experimental: true

    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: ${{ matrix.experimental }}
    name: Build - ${{ matrix.python }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture: x64

    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run formatter
      run: scripts/run_formatter.sh
      continue-on-error: true

    - name: Run tests
      run: pytest
